server:
  port: 7004
spring:
  application:
    name: BOOKING-SERVICE
  datasource:
    url: jdbc:h2:file:/temp/data/booking-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: muhammadaqib91@gmail.com
    password: prge mbcs dqex vxch
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka
  instance:
    hostname: registry

