server:
  port: 7003
spring:
  application:
    name: EVENT-SERVICE
  datasource:
    url: jdbc:h2:file:/temp/data/event-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
#  cloud:
#    config:
#      uri: http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka
  instance:
    prefer-ip-address: true
